import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "Slimkit Walking survey",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://assets.mycartpanda.com/cartx-ecomm-ui-assets/js/cpsales.js"
          strategy="afterInteractive"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
